### ISSUE TITLE
Mongock inserting duplicate changelog on index conflicts

### ISSUE THREAD

**Issue by dhavaamar** [mongock/mongock#363] opened 2021-07-13 12:01 UTC
**Describe the bug** 

When a changeSet is trying to create an index for a collection which has similar index already created, mongock is creating duplicate entry in changelog collection. Since this breaks the application startup, the re-start loop is inserting again and again.

There was a similar issue([Mongock inserting duplicate changeset on runAlways=true](https://github.com/cloudyrock/mongock/issues/322)) addressed for runAlways=true case and working but there still seems to be one other case (mentioned above) that results in duplicate changeId

**To Reproduce**

1) Create an Index for a collection
2) Add a changeSet for creating an index with the same criteria as above.
3) On application startup it inserts duplicate record with  "state" : "FAILED"

**Expected behavior**

It should not insert duplicate db changelog entry.

**Logs**

Caused by: com.github.cloudyrock.mongock.exception.MongockException: Error in method[Migration003EnsureIndexes.setDeactivatedIndex] : Command failed with error 85 (IndexOptionsConflict)

Caused by: org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 85 (IndexOptionsConflict): 'Index:

**Comment by dieppa** [comment] 2021-07-13 13:47
Hello,

I don't fully understand. If the changeSet method fails repeatedly, it's expected Mongock to get into a inifite-loop. The changeSet(or the Mongock's bug) should be fixed. Until that point I think we agree.

Currently, If Mongock executes a migration where there is a failed changeSet, it will store an entry for that changeSet with FAILED stated. If Mogock runs again, it will store another entry, **with a different executionId**, with the state FAILED. Essentially, Mongock will store a new entry every time for the same changeSet if it's failed. So that's expected to. 

If until this point every make sense, then the question really is, why the changeSet is failing? My guess is that you are trying to  create an index inside a transaction. 

As part of the version 5, which will be soon released, we are providing a mechanism to run changeSets outside the transaction, but for now, you need to run the migration without transaction with `mongock.transaction-enabled=false`

**Comment by dhavaamar** [comment] 2021-07-14 06:44
Thank you for the quick response.

Let me explain clearly. The below index is already present for a mongo collection.

![image](https://user-images.githubusercontent.com/81572944/125573400-990011cc-e359-40fb-bfbd-b46844475cd3.png)

![image](https://user-images.githubusercontent.com/81572944/125573582-26f6e368-d1d1-4ee3-95b3-691a7a030c0b.png)

As we see in the above image, index(idx_deactivated) is already created in the mongo collection for the field named "deactivated" with **sparse and background disabled**.

![image](https://user-images.githubusercontent.com/81572944/125575763-6ec1dff3-e3c4-402c-b831-8c8adfdad420.png)

When I try to create an index from changeSet with the same field "deactivated" with **sparse and background enabled**, it is throwing exception. So my application start is breaked and runs into re-start loop, which inserts one changelog entry with FAILED state for each restart try.

**Comment by dieppa** [comment] 2021-07-14 07:30
Thanks, I got it, but it's what I had in mind and that is the expected behaviour. Mongock will fail every time because is not able to run successfully that changeSet and will store a new FAILED entry every time.

At this point I am not sure if your issue is because Mongock is inserting duplicates failed entries for the changeSet, which as said is expected, or because of the fact that the changeSet fails. 

I think the changeSet is failing due to MongoDB complaining because you are creating an already existing index. I would encapsulate that piece of code within an if statement that checks if the index is already created.


However take in  mind that if you have transactions enabled(the transaction manager is injected to the context and taken by Mongock) indexes cannot be created within a transaction. We will be providing a mechanism to run changeSets outside the transaction as part of version 5, but it's still no released though.

**Comment by dhavaamar** [comment] 2021-07-15 04:38
Thank you. May I know the tentative date for the above fix version?

**Comment by dieppa** [comment] 2021-07-15 11:44
Mid august we expect an RC

**Comment by dhavaamar** [comment] 2021-08-23 11:37
Is there any update on the above bug fix?

**Comment by dieppa** [comment] 2021-08-23 14:23
Hello, it's ot really a bug fix, but we are having the RC for next week. Probably end of the next week, but ideally earlier.

We'lll keep you updated. cheers

**Comment by dieppa** [comment] 2021-09-07 11:08
Hello @dhavaamar ,

sorry I forgot to tell you, we have released a RC(5.0.7.RC). Please follow [this document](https://github.com/cloudyrock/mongock/blob/develop/QUICK_UPGRADE_VERSION_5.md) to upgrade. Please let me know anything help you need.

I assume you are stll interested in a fix for your issue. Once you have your application running with the version 5.0.7.RC, please let us know and we explain you how to do it.

Regards

**Comment by dhavaamar** [comment] 2021-09-17 05:05
Hi @dieppa We are ready with the application running with mongock version 5.0.7.RC, can you please guide us to handle the above scenario.

**Comment by dieppa** [comment] 2021-09-20 09:38
Hello @dhavaamar ,

just to recap, the issue yo are hving is that when you are creating a changeLog, this requires a DDL operation in the database, but MongoDB doesn't allo such operation to be inside a transaction.

OK. As part of the Mongock version 5, `@ChangeLog` and `@ChangeSet` annotations has been deprecated in favour of the interface `BasicChangeLog`. In the documentation that we'll be releasing soon, we explain the motivation for it.
> But none of both annotations will be removed. They will always be kept in the code for backward compatibility

To create a changeLog you need to implement this interface, which provides the same information the annotations did(methods `getId`, `changeSet`, etc.), plus a method called **rollback**, which, as its name suggest, it's a method to revert the changes. In transactional environment may not seem that interesting, but it will required for the **UNDO operation** or whenver the changeLog is deployed in a non transactional environment.

Said, that you need to implement the interface `ChangeLog`, which is an extension of `BasicChangeLog` and provides two more methods: `before` and `rollbackBefore`. One thing I didn't mention is that transactions are by default per changelog, which means that each changelog is wrapped in a transaction. This `before` will be executed just before the proper changelog starts(and therefore, the transaction). If anything wrong happens, the `rollbackBefore` will  be executed to revert these changes.


If you have any issue or question, let us know

**Comment by dieppa** [comment] 2021-09-23 14:54
Sorry, I thought I commented here, but I don't find the message

**Comment by dieppa** [comment] 2021-09-23 15:09
Please, first update to version 5.0.11.RC.

Please follow these steps:

1. Create a new migration class, but instead of annotating it with `@ChangeLog`, annotate it with `@ChangeUnit`, from package `io.mongock.api.annotations`.
2. Fill, at least, the field `id`
3. Create the method to add that index and annotate it with `@BeforeExecution`, from the same package. This method will be executed out of the transaction(before)
4. Create the method to add that index and annotate it with `@RollbackBeforeExecution`, from the same package. This method is inteded to revert the effects of  the prevous method, in case of any exception. If you don't want to revert it, just leave it empty
5. Add another method with the annotation `@Execution`(from the same package). This method is the equivalent of the old changeSet
6. Add a forth method with the annotation `@RollbackExecution`. As you probably guess, this method is to revert the effects of the `Execution` method. It' not ony used to manually rollback, when transactions are not available,it's mainly used in undo operations.

> In the method you are creating the index. One problem, obviously, is that you cannot that operation inside a transaction, but still you should check the index is not already created. If you want to execute this always, add `runAlways=true` to the`@ChangeUnit` annotation.

Any question , please, let us know
> If you want

**Comment by dieppa** [comment] 2021-09-29 16:21
Hello @dhavaamar ,

can you tell us if this worked it out for you? If so, we would like to close this ticket

**Comment by dhavaamar** [comment] 2021-09-29 19:29
Hi @dieppa Just started working on the above steps. Will update you within tomorrow. Please hold.

**Comment by dhavaamar** [comment] 2021-09-30 09:44
Hi @dieppa, Still we see duplicates after the workaround. We managed to handle it with try catch block.

**Comment by dieppa** [comment] 2021-09-30 09:56
Hello @dhavaamar ,

I think I wasn't clear enough. You will still see duplications, that's how Mongock works.

WHen running a migation, if a changeLog/changeUnit fails, it's tracked as a new entry with the relevant status(different executionId), the problem is not that, the problem is the fact that the changeUnit/changeLog is failing. I thought it was because you are creating a index inside a transaction, which is not allowed. But apparently you are having another issue and that's what needs to be solved.

I don't think try/catch is a solution as only hides the problem. 

I am starting to think that your issue is that you are creating a index that's already created...could that be possible?

**Comment by dhavaamar** [comment] 2021-09-30 10:03
@dieppa you are right, if a changeSet fails, it should insert a db entry in changeLog collection and resume the application startup process. But in this case, the application falls into rolling restart and each time an entry is inserted with failed status and this leads to infinite loop. That's the problem.

**Comment by dieppa** [comment] 2021-09-30 10:27
Hi @dhavaamar , yeah that's right and that's how Mongock works 😄 

I explain myself. First at all Mongock assume that all the changeLogs are designed to pass. The application should never start if there is any change failing. As the startup is aborted, if dpeloyed in a automated infrstructure like Kubernetes, it will try again in a loop. But the good thing about it is that the service hasn't been altered and it still coherent with the database(if it's done properly).

If you allow the application to start with failing change entries, thre is a big risk that your application and your database are not consistent.

The solution here is to fix the changeLog to make it pass.

However, although there is not really an option to ignore a failing entry, you can add `failFast=false` to the ChangeUnit annotation. What that anottation will do is basically prevent the process to fail if that change fails. In next executions will still try to execute that change, but once again, if it fails, the application startup won't abort.


Said that, I don't really understand your scenario, where you have a failing change that you want to keep failing, instead of fixing...I feel I am missing something


Anyway I hope this helps you 😉

**Comment by dhavaamar** [comment] 2021-10-01 11:36
@dieppa oh that's a great support from you! I understood the point. As I said in the previous reply, each restart try inserts a db entry with FAILED status, which leads to infinite entries in dbChangeLog collection as application runs into infinite restart loop. Since we have many applications running parallelly with same db, when one application fails with above issue, other applications startup also getting failed with "duplicate entry"(in dbChangeLog collection) message. That's a big trouble again.

**Comment by dieppa** [comment] 2021-10-01 13:39
Hi @dhavaamar ,

but I don't think the problem is because of a duplication. Although they entries look very similar, with same status, they have different execution id. I just said that becaise I think you believe that the error is due to that duplicate entry insertion. I really doubt it's the case.

As said, I really think that the changeLog is faliing for whatever reason and Mongock inserts that failed entry. but even without inserting, your application would start in a loop bacause the changeLog fails(for other reason), forcing Mongock to fail which abort the startup.

If you want me to provide a bit more help, I would need some extract of the duplicated entries in the mongockChangeLog collectio(that's not sensitive data) and the changeUnit failing. I think with that I can figure it out as I am quite confused to be honest.

**Comment by dieppa** [comment] 2021-11-09 15:11
was it fixed?

**Closed** 2021-11-15 22:47 UTC
